# Generated by Django 4.2.15 on 2025-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0002_game_vote_delete_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='game',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='game_order',
            field=models.JSONField(default=list),
        ),
    ]
